### ISSUE TITLE
can you provide objective-c version for ios (iphone,ipad)??

### ISSUE THREAD

**Issue by cloudjanak** [JorenSix/TarsosDSP#39]

**Comment by JorenSix** [comment]
Hi, i have no plans tot provider an objectieve c version of this library. It should however be relatively straightforward to translate the code. If you do this it would be nice to respect the license.

Alternatively it should be possible to run TarsosDSP on iOS using the Codename One compiler. Please let me know if you get it running since I do not know if that actually works.

**Comment by cloudjanak** [comment]
i fails,i need your help on this.My Collage project is stucked.

**Comment by JorenSix** [comment]
See my previous post.
