### ISSUE TITLE
Android - BeatRootSpectralFluxOnsetDetector - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by paillardf** [JorenSix/TarsosDSP#61]
Hi,

I am trying to detect the beat of a sample with a BeatRootSpectralFluxOnsetDetector but my code raise a ArrayIndexOutOfBoundsException. It appears to be due to the durationInFrames value -1000 with a FIX ME comment on it.
Could you help me please on this.
Here is my code :

~~~~
File externalStorage = Environment.getExternalStorageDirectory();
File mp3 = new File(externalStorage.getAbsolutePath(), "/Download/song.mp3");
AudioDispatcher = AudioDispatcherFactory.fromPipe(mp3.getAbsolutePath(), 44100, 2048, 2048-441);
adp.setZeroPadFirstBuffer(true);
BeatRootSpectralFluxOnsetDetector b = new BeatRootSpectralFluxOnsetDetector(adp, 2048, 441);
                b.setHandler(new OnsetHandler() {
                    @Override
                    public void handleOnset(double time, double salience) {
                        double roundedTime = Math.round(time * 100) / 100.0;
                        Event e = newEvent(roundedTime, 0);
                        e.salience = salience;
                        onsetList.add(e);
                    }
                });
adp.addAudioProcessor(b);
adp.run();

~~~

Thx

**Comment by adrienjt** [comment]
Bonjour Florian, you're not alone. I get the same ArrayIndexOutOfBoundsException with BeatRootSpectralFluxOnsetDetector and ComplexOnsetDetector in my Android implementation. Have you found a solution?
Joren, great job on TarsosDSP! (I got some success using the PercussionOnsetDetector, yet it's not the kind of onset detector I want to use eventually.) Your help would be very much appreciated.

**Comment by paillardf** [comment]
No solution for me. My project is in standby mode. I have investigated the git history. The problem come from a major refactoring and it is realy complex to understand every aspect of it. I hope Joren will have the time to finish it.

**Comment by TeyCode** [comment]
I've copied the entire BeatRootSpectralFluxOnsetDetector class inside my project and changed the -1000 value to a temporary value of 24000 (my sample mp3 gave me about 23965). Althought it completes without a single error, there is a memory leak somewhere. GC went bananas after the application hit about 89MB. Heap Table shows that a 8-byte array (long[] , double[]) and a 1-byte array (byte[] , boolean[]) consumes about 84MB of memory. Could anybody try the same until Joren publishes an update? I'm having the same issues here too.

**Comment by JorenSix** [comment]
Hi,

The problem with the `BeatRootSpectralFluxOnsetDetector ` is that it needs a duration in frames. This is problematic in the TarsosDSP project setting since all  `AudioProcessor `s support streaming from microphone (so it is not known how many frames there are going to be). This is due to the fact that the code has been copied from the [GPL'd Beatroot project from Simon Dixon](http://www.eecs.qmul.ac.uk/~simond/beatroot/)

However there is a workaround: Beatroot works by finding patterns in onsets, but where these onsets come from does not matter. The `BeatRootSpectralFluxOnsetDetector` is the one used in Beatroot originally but the `ComplexOnsetDetector` works better on most music signals (see the literature referenced in the readme and code). So something like the following code (from the FeatureExtractor example) should work: 

    @Override
    public boolean run(String... args) throws UnsupportedAudioFileException, IOException {
    	String inputFile = args[1];
    	File audioFile = new File(inputFile);
    	int size = 512;
    	int overlap = 256;
    	AudioDispatcher dispatcher = AudioDispatcherFactory.fromFile(audioFile, size, overlap);
    	
    	ComplexOnsetDetector detector = new ComplexOnsetDetector(size);
    	BeatRootOnsetEventHandler handler = new BeatRootOnsetEventHandler();
    	detector.setHandler(handler);
    	
    	dispatcher.addAudioProcessor(detector);
    	dispatcher.run();
    	
    	handler.trackBeats(this);
    	
    	return true;
    }
    
    @Override
    public void handleOnset(double time, double salience) {
    	System.out.println(time);
    }

On Android the same code should work. As said before, this is a workaround. A clean fix would be to make the `BeatRootSpectralFluxOnsetDetector` support streaming. The current implementation is in there to make it 100% compatible with the original Beatroot source.

Hopfully this helps to circumvent the problem.

Joren

**Comment by JorenSix** [comment]
@paillardf @adrienjt @TeyCode please let me know if the workaround suffices in your use-case.

**Comment by paillardf** [comment]
@JorenSix Thank you. it work perfectly

**Comment by adrienjt** [comment]
Yes, thank you, it works like a charm! On Android I replaced AudioDispatcherFactory.fromFile by AudioDispatcherFactory.**fromPipe**.
